default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: hnews_development

test:
  <<: *default
  database: hnews_test

production:
  <<: *default
  database: hnews_production
