# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9f169f4711678de1c386a40c6e91b46c18497f1889afeb38ab75ac3d799e0e247f70b343e38fca0a6618100837d621a6f934221000b350b253990a7f6a52aa2

test:
  secret_key_base: 8149e5773c7ca56869755ef8625cadb6d1947860b0d2b0f20d4179392cd6173feaef0949fe424ae7c9415297b39c2d1fe7032675fa9eba0e4576d6570d61878c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
